---
title: "Introducción"
author: "Villaseñor-Derbez, J.C."
date: "Septiembre, 2017"
output:
  ioslides_presentation:
    incremental: yes
    transition: faster
    widescreen: yes
    css: myCSS.css
bibliography: exported-references.bib
---

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script>
    $(document).ready(function() {
    $('slide:not(.title-slide, .backdrop, .segue)').append('<footer></footer>');    
    $('footer').attr('label', 'Intro');

  })
</script>

<style>
  footer:after {
    font-size: 12pt;
    content: attr(label);
    position: absolute;
    bottom: 20px;
    left: 60px;
    line-height: 1.9;
    display: block;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Presentaciones

## Historia de MAREA

- MAREA : Aplicación para Evaluación de Reservas Marinas (Marine Reserve Evaluation App)
- Uno de los productos de TURFeffect + COBI + Stanford + SFG + ASU
- Objetivos fueron:
    - Estandarizar la evaluación de RM en México ([Manual](https://www.researchgate.net/publication/317840836_Una_guia_para_evaluar_la_efectividad_de_las_zonas_de_no_pesca_en_Mexico))
        - Objetivos
        - Indicadores
        - Análisis
    - Hacer el trabajo accesible y replicable

## Objetivos del curso

- No es un curso detallado de evaluación de RM o acciones de manejo
- Aprender a usar MAREA y el marco teórico propuesto
- Qué hacer y qué no hacer


- MAREA no es la solución a todos los males

## Vista previa de MAREA

[MAREA](turfeffect.shinyapps.io)

## Esquema del curso {.smaller}

- Historia de la evaluación de RM (~ 30 min)
- Objetivos e indicadores (~ 30 min)
- Datos y formato de datos (~ 40 min)

- **Comida** (~ 90 min)

- Análisis (~ 75 min)
- Uso de MAREA (~ 60 min)
    - Demostración detallada
    - Ejercicios
- Interpretación de resultados (~ 20 min)
- Resumen (~ 15 min)
- Descansos de 5 - 10 min entre bloques
- Tiempo estimado (~ 6.5 hrs)

## Generalidades

- Participaciones bienvenidas
- Entre más preguntas mejor
- Interrupciones ordenadas en cualquier momento

# [Bloque 1](./bloque1.html)



